### ISSUE TITLE
IOError: File ./lenet5.ckpt.meta does not exist.

### ISSUE THREAD

**Issue by dgtlmoon** [setezzy/image-retrieval#2]
Where do I get this file? How do I get it?
I ran

`$ python retrieval.py 100 s_p_noise`

...

```Traceback (most recent call last):
  File "retrieval.py", line 124, in <module>
    retrieval()
  File "retrieval.py", line 37, in retrieval
    saver = tf.train.import_meta_graph('./lenet5.ckpt.meta')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1666, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1678, in _import_meta_graph_with_return_elements
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 633, in read_meta_graph_file
    raise IOError("File %s does not exist." % filename)
IOError: File ./lenet5.ckpt.meta does not exist.
```

**Comment by setezzy** [comment]
You need to train your own network.
